apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://DevToppers@dev.azure.com/DevToppers/Cloud%20Automation/_git/AWS%20Application
    targetRevision: HEAD
    path: Jenkins/Helm/jenkins-k8
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-team-1