apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SanLatkar/argocd-example-apps
    targetRevision: HEAD
    path: helm-guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default